### PR TITLE
sanitize string before parse (custom to my needs, but may be useful)

### PR DESCRIPTION
**Pull request by Korkey128k**
All tests passed.
Not really sure if this would be useful or if this is the way you would do it, but figured I'd contribute it anyway. I'm sure there are other sanitations that could be done for parse as well.

### CODE REVIEW

**Comment by mhuggins** [comment]
Thanks for this! I'm interested in deciphering the regex, but I'm open to including this.

**Comment by Korkey128k** [comment]
I was trying to find where you do the fractions in the code to include the vulgar check there, but i couldn't. I'd love to refactor this later.

I included the regex to spark some conversation. I think `parse` would be much more useful if it had some power to clean up a string. (which it already does a pretty good job of)

**Comment by mhuggins** [comment]
Sorry I haven't gotten to take a closer look at this yet.  It's been a hectic work week.  Some of the regex matching sounds like it's really specific to your use case, so I think there might be a better way of handling that either in a service layer prior to hitting the gem, or maybe in some kind of helper callback that can be added to the gem.  I haven't gotten to look at the code in more detail to see what makes more sense though.

Regarding the fraction conversions, I think the gem should handle unicode fraction characters as well, so that's definitely a good contribution.  I just want to take another look at the code (maybe this weekend) to see if your approach makes the most sense vs. fitting it into the parsing logic elsewhere.

**Comment by mhuggins** [comment]
FWIW your fraction character mapping probably is the easiest thing.  The other option would be to make [this regex](https://github.com/mhuggins/ruby-measurement/blob/master/lib/ruby-measurement/measurement.rb#L8) aware of all possible fractions, which would become quite complex.

**Comment by mhuggins** [comment]
@Korkey128k I'm going to close this in favor of #7, which I just merged in and released as version 1.2.3.  Thanks for your help, and sorry about the delay!

**Comment by Korkey128k** [comment]
Don't sweat it, glad I could help!

**Pull request closed without merging**
