### PR TITLE
Add compare methods

### PR DESCRIPTION
**Pull request by EdmundLeex**

### CODE REVIEW

**Comment by mhuggins** [comment]
I'm okay with adding the `<=>` operator, but this change [breaks existing behavior](https://travis-ci.org/mhuggins/ruby-measurement/jobs/281411252) for `Measurement#==`.  Previously, if the unit or class differed, then the return value was `false`, but it is now raising `ArgumentError`.

The [Comparable documentation](https://ruby-doc.org/core-2.2.3/Comparable.html) states that if two values cannot be compared, then `nil` should be returned:

> If the other object is not comparable then the <=> operator should return nil.

I think if you were to make that change rather than raising an error, then perhaps the test suite would pass again.

**Comment by EdmundLeex** [comment]
Hmm.. this actually breaks on ruby version older than 2.0.0.

According to https://ruby-doc.org/core-2.0.0/Comparable.html#method-i-3D-3D:

> Even if obj <=> other raised an exception, the exception is ignoread and returns false.

**Comment by EdmundLeex** [comment]
Do we want this to be backward compatible for versions older than 2.0?

**Comment by mhuggins** [comment]
I would prefer this to work for 1.9.3 as well, if possible.  Does returning `nil` in the scenario I called out make it work?

**Comment by EdmundLeex** [comment]
Look like the specs actually failed at installing the gem. Can you take a look?

**Comment by mhuggins** [comment]
@EdmundLeex I just merged #14, which fixes the travis build.  If you rebase this branch from master, your tests should (hopefully) pass.

**Comment by EdmundLeex** [comment]
@mhuggins Works out very nice!. This is ready.

**Comment by mhuggins** [comment]
@EdmundLeex Better late than never, hopefully.  I just published this change under [version 1.3.0](https://rubygems.org/gems/ruby-measurement).  Thank you!

**Pull request merged**
